name: AntiElytraInEnd
version: '${project.version}'
main: cn.paper_card.anti_elytra_in_end.AntiElytraInEnd
api-version: 1.20
author: Paper99
description: 允许管理员设置玩家是否可以在末地外岛使用鞘翅飞行
folia-supported: true

commands:
  anti-elytra-in-end:
    permission: anti-elytra-in-end.command
    description: 末地鞘翅飞行开关命令

permissions:
  anti-elytra-in-end.command:
    default: true
